### ISSUE TITLE
Possible to get working for Gemini Cli?

### ISSUE THREAD

**Issue by peter-stuart-turner** [zereight/gitlab-mcp#139]
Have tried, doesnt seem to work

**Comment by iwakitakuma33** [comment]
@VikashLoomba 
@peter-stuart-turner 
Could you try this in your local?

https://github.com/zereight/gitlab-mcp/pull/144

**Comment by VikashLoomba** [comment]
@iwakitakuma33 This comment might be helpful for a quick fix: https://github.com/google-gemini/gemini-cli/issues/1481#issuecomment-3042209915

**Comment by VikashLoomba** [comment]
Update: Was able to getting it working by using GITLAB_READ_ONLY_MODE=true when starting the server

**Comment by schiob** [comment]
@iwakitakuma33 

I tried with the main branch and get the same error:
```
Failed to list or register tools for MCP server 'gitlab': TypeError: fieldValue.toUpperCase is not a function
No tools registered from MCP server 'gitlab'. Closing connection.
```

This is my settings.json for gemini
```
{
  "theme": "Default",
  "selectedAuthType": "oauth-personal",
  "mcpServers": {
    "gitlab": {
      "command": "tsx",
      "args": [
        "/path/to/gitlab-mcp/index.ts"
      ],
      "cwd": "/path/to/gitlab-mcp",
      "env": {
        "GITLAB_PERSONAL_ACCESS_TOKEN": "<token>",
        "GITLAB_API_URL": "https://gitlab.com/api/v4",
        "GITLAB_READ_ONLY_MODE": "false",
        "USE_GITLAB_WIKI": "false",
        "USE_MILESTONE": "false",
        "USE_PIPELINE": "false"
      }
    }
  }
}
```

This same settings works with gemini 0.1.10 but doesn't work with version 0.1.11

**Comment by iwakitakuma33** [comment]
@peter-stuart-turner @VikashLoomba @dwirandyh @schiob 

this issue is not solved.
so reopened.

I fixed it https://github.com/google-gemini/gemini-cli/issues/1481#issuecomment-3075285900.

**Comment by iwakitakuma33** [comment]
released 
https://github.com/google-gemini/gemini-cli/issues/1481#issuecomment-3082042841

**Comment by iwakitakuma33** [comment]
https://github.com/google-gemini/gemini-cli/issues/1481#issuecomment-3082534931

**Comment by b3nw** [comment]
This is still happening in 0.1.12

```
$ gemini -version
0.1.12
```

```
$ gemini -c
Failed to list or register tools for MCP server 'GitLab': TypeError: fieldValue.toUpperCase is not a function
No tools registered from MCP server 'GitLab'. Closing connection.
```

What version of gemini-cli works? 
The latest npx version has different breaking bug making it un-usable 😩

**Comment by b3nw** [comment]
this is resolved in 0.1.13 🎉 which was released today finally.
